services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
